import { describe, it, expect, vi } from "vitest";

// Stub the tools barrel so the module loads in node; getAll is injected in tests,
// and deleteAnnotation calls the (mocked) real removeAnnotation.
const { removeAnnotation } = vi.hoisted(() => ({
  removeAnnotation: vi.fn(),
}));
vi.mock("@cornerstonejs/tools", () => ({
  annotation: { state: { getAllAnnotations: vi.fn(() => []), removeAnnotation } },
}));

import {
  getAnnotationDeleteTargets,
  deleteAnnotation,
  type OverlayAnnotation,
} from "../src/cornerstone/annotation-overlay";

const vp = {
  getCurrentImageId: () => "img-1",
  // identity-ish projection: x,y from world, ignore z
  worldToCanvas: ([x, y]: [number, number, number]) => [x * 10, y * 10] as [number, number],
};

const ann = (over: Partial<OverlayAnnotation> = {}): OverlayAnnotation => ({
  annotationUID: "a1",
  metadata: { toolName: "Length", referencedImageId: "img-1" },
  data: { handles: { points: [[1, 2, 0]], textBox: { worldPosition: [3, 4, 0] } } },
  ...over,
});

describe("getAnnotationDeleteTargets", () => {
  it("returns one target per tracked, on-slice annotation anchored at the label box", () => {
    const out = getAnnotationDeleteTargets(vp, () => [ann()]);
    expect(out).toEqual([{ uid: "a1", toolName: "Length", canvas: { x: 30, y: 40 } }]);
  });

  it("falls back to points[0] when there is no textBox", () => {
    const a = ann({ data: { handles: { points: [[1, 2, 0]] } } });
    const out = getAnnotationDeleteTargets(vp, () => [a]);
    expect(out[0].canvas).toEqual({ x: 10, y: 20 });
  });

  it("skips auto-generated, unknown tools, and annotations on other slices", () => {
    const auto = ann({ annotationUID: "x", autoGenerated: true });
    const unknown = ann({ annotationUID: "y", metadata: { toolName: "Crosshairs", referencedImageId: "img-1" } });
    const offSlice = ann({ annotationUID: "z", metadata: { toolName: "Length", referencedImageId: "img-2" } });
    const out = getAnnotationDeleteTargets(vp, () => [auto, unknown, offSlice]);
    expect(out).toEqual([]);
  });
});

describe("deleteAnnotation", () => {
  it("removes by uid and ignores an empty uid", () => {
    deleteAnnotation("a1");
    expect(removeAnnotation).toHaveBeenCalledWith("a1");
    removeAnnotation.mockClear();
    deleteAnnotation("");
    expect(removeAnnotation).not.toHaveBeenCalled();
  });
});
