import { describe, it, expect, vi } from "vitest";

// measurements.ts imports the cornerstone barrels at module load; stub them so
// the pure collect/format logic runs in node. collectMeasurements is exercised
// via its injected getter, so annotation.state is never actually called here.
vi.mock("@cornerstonejs/tools", () => ({
  annotation: { state: { getAllAnnotations: vi.fn(() => []) } },
  Enums: {
    Events: { ANNOTATION_COMPLETED: "a", ANNOTATION_MODIFIED: "b", ANNOTATION_REMOVED: "c" },
  },
}));
vi.mock("@cornerstonejs/core", () => ({
  eventTarget: { addEventListener: vi.fn(), removeEventListener: vi.fn() },
}));

import {
  collectMeasurements,
  measurementsToJson,
  measurementsToCsv,
  type Measurement,
} from "../src/cornerstone/measurements";

// Build a flat Annotation[] the way cornerstone's getAllAnnotations() returns it.
const ann = (over: Record<string, unknown>) => ({
  annotationUID: "uid",
  metadata: { toolName: "Length", referencedImageId: "img1", FrameOfReferenceUID: "FOR1" },
  data: { handles: { points: [] }, cachedStats: {} },
  ...over,
});

describe("collectMeasurements", () => {
  it("normalizes a Length annotation (length in mm)", () => {
    const got = collectMeasurements(() => [
      ann({
        metadata: { toolName: "Length", referencedImageId: "img1", FrameOfReferenceUID: "FOR1" },
        data: {
          label: "scar",
          handles: {
            points: [
              [1, 2, 3],
              [4, 5, 6],
            ],
          },
          cachedStats: { "imageId:img1": { length: 42.5, unit: "mm" } },
        },
      }),
    ]);
    expect(got).toHaveLength(1);
    expect(got[0]).toMatchObject({
      tool: "Length",
      label: "scar",
      imageId: "img1",
      frameOfReferenceUID: "FOR1",
    });
    expect(got[0].stats).toEqual([
      { target: "imageId:img1", name: "length", value: 42.5, unit: "mm" },
    ]);
    expect(got[0].points).toEqual([
      [1, 2, 3],
      [4, 5, 6],
    ]);
  });

  it("keeps Angle in degrees (no radian conversion) and skips incomplete angles", () => {
    const [complete] = collectMeasurements(() => [
      ann({ metadata: { toolName: "Angle" }, data: { cachedStats: { t: { angle: 90 } } } }),
    ]);
    expect(complete.stats).toEqual([{ target: "t", name: "angle", value: 90, unit: "deg" }]);

    const [incomplete] = collectMeasurements(() => [
      ann({
        metadata: { toolName: "Angle" },
        data: { cachedStats: { t: { angle: "Incomplete Angle" } } },
      }),
    ]);
    expect(incomplete.stats).toEqual([]);
  });

  it("extracts ROI area + intensity stats with their stored units, dropping undefined", () => {
    const [m] = collectMeasurements(() => [
      ann({
        metadata: { toolName: "RectangleROI" },
        data: {
          cachedStats: {
            t: {
              area: 12.3,
              areaUnit: "mm²",
              mean: -40,
              max: 100,
              min: -120,
              stdDev: 30,
              modalityUnit: "HU",
            },
          },
        },
      }),
    ]);
    expect(m.stats).toEqual([
      { target: "t", name: "area", value: 12.3, unit: "mm²" },
      { target: "t", name: "mean", value: -40, unit: "HU" },
      { target: "t", name: "max", value: 100, unit: "HU" },
      { target: "t", name: "min", value: -120, unit: "HU" },
      { target: "t", name: "stdDev", value: 30, unit: "HU" },
    ]);
  });

  it("handles a multi-channel Probe value array", () => {
    const [m] = collectMeasurements(() => [
      ann({
        metadata: { toolName: "Probe" },
        data: { cachedStats: { t: { value: [10, 20], modalityUnit: ["R", "G"] } } },
      }),
    ]);
    expect(m.stats).toEqual([
      { target: "t", name: "value[0]", value: 10, unit: "R" },
      { target: "t", name: "value[1]", value: 20, unit: "G" },
    ]);
  });

  it("skips unknown tools and auto-generated annotations, and never throws on malformed input", () => {
    const got = collectMeasurements(() => [
      ann({ metadata: { toolName: "SegmentationDisplay" } }),
      ann({ autoGenerated: true }),
      { annotationUID: "x" }, // no metadata/data
    ]);
    expect(got).toEqual([]);
  });
});

describe("measurementsToJson", () => {
  it("wraps measurements in a provenance envelope with a pinned timestamp", () => {
    const m: Measurement[] = [
      {
        annotationUID: "u1",
        tool: "Length",
        label: "",
        imageId: "i",
        frameOfReferenceUID: "f",
        stats: [],
        points: [],
      },
    ];
    const doc = JSON.parse(measurementsToJson(m, () => "2026-06-26T00:00:00.000Z"));
    expect(doc).toMatchObject({
      schema: "orbidicom.measurements/v1",
      exportedAt: "2026-06-26T00:00:00.000Z",
      count: 1,
    });
    expect(doc.measurements).toHaveLength(1);
  });
});

describe("measurementsToCsv", () => {
  const base = { annotationUID: "u1", tool: "Length", imageId: "i1", frameOfReferenceUID: "f1" };

  it("emits a header, one row per stat, with CRLF terminators", () => {
    const csv = measurementsToCsv([
      {
        ...base,
        label: "a",
        stats: [
          { target: "t", name: "length", value: 5, unit: "mm" },
          { target: "t", name: "extra", value: 2, unit: "" },
        ],
        points: [[1, 2, 3]],
      },
    ]);
    const lines = csv.split("\r\n");
    expect(lines[0]).toBe(
      "annotationUID,tool,label,imageId,frameOfReferenceUID,target,statName,statValue,statUnit,points,pointCount",
    );
    expect(lines).toHaveLength(3); // header + 2 stat rows
    expect(lines[1]).toBe("u1,Length,a,i1,f1,t,length,5,mm,1 2 3,1");
  });

  it("emits one empty-stat row for an annotation with no finite stats", () => {
    const csv = measurementsToCsv([{ ...base, label: "x", stats: [], points: [] }]);
    const lines = csv.split("\r\n");
    expect(lines).toHaveLength(2); // header + one row
    expect(lines[1]).toBe("u1,Length,x,i1,f1,,,,,,0");
  });

  it("escapes commas, quotes and newlines per RFC-4180", () => {
    const csv = measurementsToCsv([
      {
        ...base,
        label: 'a,"b"\nc',
        stats: [{ target: "t", name: "length", value: 1, unit: "mm" }],
        points: [],
      },
    ]);
    expect(csv.split("\r\n")[1]).toContain('"a,""b""\nc"');
  });
});
