import "./theme.css";
export { default as Viewer } from "./components/Viewer.vue";
export { default as Toolbar } from "./components/Toolbar.vue";
export { default as SeriesRail } from "./components/SeriesRail.vue";
export { default as MetaPanel } from "./components/MetaPanel.vue";
export { default as PdfView } from "./components/PdfView.vue";
export { default as SrView } from "./components/SrView.vue";
export { default as LangSwitcher } from "./components/LangSwitcher.vue";
export { default as StudyList } from "./components/StudyList.vue";
export { default as Controls } from "./components/Controls.vue";
export { setLang, getLang, t, isRtl, dir, LOCALES, type I18nKey, type Locale } from "./i18n";
