/**
 * Per-annotation delete support for the viewport overlay. Framework-agnostic:
 * {@link getAnnotationDeleteTargets} projects each tracked, on-slice measurement's
 * label anchor to canvas pixels so the UI can float an "x" there, and
 * {@link deleteAnnotation} removes one annotation through Cornerstone's normal
 * (unguarded) path — which the annotation-history REMOVED listener records as an
 * undoable delete (see annotation-history.ts).
 */
import { annotation, Enums as csToolsEnums } from "@cornerstonejs/tools";
import { eventTarget, Enums as csEnums } from "@cornerstonejs/core";

/** Mirrors the tracked set in measurements.ts / annotation-history.ts. */
const KNOWN_TOOLS = new Set(["Length", "Angle", "RectangleROI", "EllipticalROI", "Probe"]);

/** Minimal annotation shape this module reads (avoids deep Cornerstone type coupling). */
export interface OverlayAnnotation {
  annotationUID?: string;
  autoGenerated?: boolean;
  metadata?: { toolName?: string; referencedImageId?: string };
  data?: { handles?: { points?: number[][]; textBox?: { worldPosition?: number[] } } };
}

/** The slice of a Cornerstone viewport this module needs (structurally satisfied by IStackViewport). */
export interface OverlayViewport {
  worldToCanvas(world: [number, number, number]): [number, number];
  getCurrentImageId(): string | undefined;
}

/** Where to draw one delete control: canvas pixels relative to the viewport's canvas. */
export interface DeleteTarget {
  uid: string;
  toolName: string;
  canvas: { x: number; y: number };
}

/**
 * Build the list of delete controls for the annotations currently visible in
 * `viewport`. `getAll` is injectable for tests; it defaults to Cornerstone's global
 * annotation state. Off-slice, auto-generated, and non-measurement annotations are skipped.
 */
export function getAnnotationDeleteTargets(
  viewport: OverlayViewport,
  getAll: () => OverlayAnnotation[] = () =>
    annotation.state.getAllAnnotations() as unknown as OverlayAnnotation[],
): DeleteTarget[] {
  const currentImageId = viewport.getCurrentImageId();
  const out: DeleteTarget[] = [];
  for (const a of getAll() ?? []) {
    const toolName = a?.metadata?.toolName ?? "";
    if (!KNOWN_TOOLS.has(toolName) || a?.autoGenerated === true) continue;
    if (!a.annotationUID) continue; // no uid -> a delete button that can't delete anything
    const ref = a.metadata?.referencedImageId;
    // Only annotations drawn on the slice currently shown (Cornerstone draws only those too).
    if (currentImageId && ref && ref !== currentImageId) continue;
    const anchor = a.data?.handles?.textBox?.worldPosition ?? a.data?.handles?.points?.[0];
    if (!anchor || anchor.length < 3) continue;
    const [x, y] = viewport.worldToCanvas(anchor.slice(0, 3) as [number, number, number]);
    if (!Number.isFinite(x) || !Number.isFinite(y)) continue;
    out.push({ uid: a.annotationUID ?? "", toolName, canvas: { x, y } });
  }
  return out;
}

/**
 * Remove a single annotation by UID. Goes through Cornerstone's normal removal so
 * the history's ANNOTATION_REMOVED listener records an undoable delete. No-op for "".
 */
export function deleteAnnotation(uid: string): void {
  if (uid) annotation.state.removeAnnotation(uid);
}

/**
 * Subscribe to the Cornerstone render events that should reposition a viewport's
 * annotation overlay: the element's image renders + slice changes, and the global
 * annotation render (filtered to this viewport). Keeping this wiring in core lets
 * the UI layer stay Cornerstone-free. Returns a teardown fn.
 * @param getViewportId reads the current viewport id, to filter the global event
 */
export function subscribeOverlayReposition(
  element: HTMLElement,
  getViewportId: () => string | undefined,
  cb: () => void,
): () => void {
  const onElement = () => cb();
  const onAnnotationRender = (e: Event) => {
    const id = (e as CustomEvent).detail?.viewportId as string | undefined;
    const ours = getViewportId();
    if (id && ours && id !== ours) return; // a different viewport's render
    cb();
  };
  element.addEventListener(csEnums.Events.IMAGE_RENDERED, onElement as EventListener);
  element.addEventListener(csEnums.Events.STACK_NEW_IMAGE, onElement as EventListener);
  eventTarget.addEventListener(
    csToolsEnums.Events.ANNOTATION_RENDERED,
    onAnnotationRender as EventListener,
  );
  return () => {
    element.removeEventListener(csEnums.Events.IMAGE_RENDERED, onElement as EventListener);
    element.removeEventListener(csEnums.Events.STACK_NEW_IMAGE, onElement as EventListener);
    eventTarget.removeEventListener(
      csToolsEnums.Events.ANNOTATION_RENDERED,
      onAnnotationRender as EventListener,
    );
  };
}
