/**
 * Annotation undo / redo — a framework-agnostic history of the user's annotation
 * actions. Scope: **create** (a measurement was drawn) and **delete** (a
 * measurement was removed). Moving/resizing an existing annotation is *not* a
 * tracked step, but such edits survive an undo→redo round trip because undoing a
 * create snapshots the annotation's *current* state first (see {@link createAnnotationHistory}).
 *
 * The controller is pure logic over an injected {@link AnnotationStateAdapter}, so
 * it is fully testable in node. {@link startAnnotationHistory} wires the default
 * singleton ({@link annotationHistory}) to Cornerstone's global annotation events;
 * the Vue layer drives undo()/redo() and re-renders viewports afterwards.
 */
import { annotation, Enums as csToolsEnums } from "@cornerstonejs/tools";
import { eventTarget } from "@cornerstonejs/core";

/** The measurement tools whose create/delete we track (mirrors measurements.ts). */
const KNOWN_TOOLS = new Set(["Length", "Angle", "RectangleROI", "EllipticalROI", "Probe"]);

/** Minimal shape we read from a Cornerstone annotation (cloned opaquely otherwise). */
export interface HistoryAnnotation {
  annotationUID?: string;
  autoGenerated?: boolean;
  metadata?: { toolName?: string; FrameOfReferenceUID?: string };
  [k: string]: unknown;
}

/** The slice of Cornerstone's `annotation.state` the history needs (injectable for tests). */
export interface AnnotationStateAdapter {
  getAnnotation(uid: string): HistoryAnnotation | undefined;
  addAnnotation(annotation: HistoryAnnotation, groupSelector: string): void;
  removeAnnotation(uid: string): void;
}

type Entry =
  | { kind: "create"; uid: string; group: string; snapshot?: HistoryAnnotation }
  | { kind: "delete"; uid: string; group: string; snapshot: HistoryAnnotation };

export interface AnnotationHistory {
  /** Record that the user drew a new annotation (called from the COMPLETED listener). */
  recordCreate(uid: string, groupSelector: string): void;
  /** Record that the user deleted an annotation (called from the REMOVED listener). */
  recordDelete(annotation: HistoryAnnotation): void;
  /** Undo the most recent action; returns false if there's nothing to undo. */
  undo(): boolean;
  /** Redo the most recently undone action; returns false if there's nothing to redo. */
  redo(): boolean;
  canUndo(): boolean;
  canRedo(): boolean;
  /** Clear both stacks. Does not mutate annotation state. */
  reset(): void;
  /** Subscribe to stack changes; returns an unsubscribe fn. */
  subscribe(cb: () => void): () => void;
}

const clone = <T>(v: T): T =>
  typeof structuredClone === "function" ? structuredClone(v) : (JSON.parse(JSON.stringify(v)) as T);

/**
 * Build a history controller over the given annotation-state adapter.
 *
 * The `applying` guard is essential: undo/redo mutate state via the adapter, and
 * `removeAnnotation` re-fires Cornerstone's ANNOTATION_REMOVED *synchronously*.
 * Without the guard, the REMOVED listener would record our own operation as a new
 * user delete and corrupt the stacks. While `applying` is set, recording no-ops.
 */
export function createAnnotationHistory(adapter: AnnotationStateAdapter): AnnotationHistory {
  let undoStack: Entry[] = [];
  let redoStack: Entry[] = [];
  let applying = false;
  const subs = new Set<() => void>();
  const notify = () => {
    for (const cb of subs) cb();
  };

  function recordCreate(uid: string, groupSelector: string): void {
    if (applying || !uid) return;
    undoStack.push({ kind: "create", uid, group: groupSelector });
    redoStack = [];
    notify();
  }

  function recordDelete(ann: HistoryAnnotation): void {
    if (applying) return;
    const uid = ann.annotationUID ?? "";
    if (!uid) return;
    undoStack.push({
      kind: "delete",
      uid,
      group: ann.metadata?.FrameOfReferenceUID ?? "",
      snapshot: clone(ann),
    });
    redoStack = [];
    notify();
  }

  function apply(fn: () => void): void {
    applying = true;
    try {
      fn();
    } finally {
      applying = false;
    }
  }

  function undo(): boolean {
    const entry = undoStack.pop();
    if (!entry) return false;
    apply(() => {
      if (entry.kind === "create") {
        // Snapshot the latest state so a redo restores any edits made since drawing.
        const live = adapter.getAnnotation(entry.uid);
        if (live) entry.snapshot = clone(live);
        adapter.removeAnnotation(entry.uid);
      } else {
        adapter.addAnnotation(entry.snapshot, entry.group);
      }
    });
    redoStack.push(entry);
    notify();
    return true;
  }

  function redo(): boolean {
    const entry = redoStack.pop();
    if (!entry) return false;
    apply(() => {
      if (entry.kind === "create") {
        if (entry.snapshot) adapter.addAnnotation(entry.snapshot, entry.group);
      } else {
        adapter.removeAnnotation(entry.uid);
      }
    });
    undoStack.push(entry);
    notify();
    return true;
  }

  function reset(): void {
    undoStack = [];
    redoStack = [];
    notify();
  }

  return {
    recordCreate,
    recordDelete,
    undo,
    redo,
    canUndo: () => undoStack.length > 0,
    canRedo: () => redoStack.length > 0,
    reset,
    subscribe: (cb) => {
      subs.add(cb);
      return () => {
        subs.delete(cb);
      };
    },
  };
}

/* ------------------------------------------------------------------ *
 * Default singleton, wired to Cornerstone's global annotation events.
 * ------------------------------------------------------------------ */

const realAdapter: AnnotationStateAdapter = {
  getAnnotation: (uid) =>
    annotation.state.getAnnotation(uid) as unknown as HistoryAnnotation | undefined,
  addAnnotation: (ann, group) => {
    annotation.state.addAnnotation(ann as never, group as never);
  },
  removeAnnotation: (uid) => {
    annotation.state.removeAnnotation(uid);
  },
};

/** The viewer-wide annotation history (Cornerstone annotation state is global). */
export const annotationHistory = createAnnotationHistory(realAdapter);

const annotationOf = (evt: Event): HistoryAnnotation | undefined =>
  (evt as CustomEvent<{ annotation?: HistoryAnnotation }>).detail?.annotation;

const isTracked = (a: HistoryAnnotation | undefined): a is HistoryAnnotation =>
  !!a && KNOWN_TOOLS.has(a.metadata?.toolName ?? "") && a.autoGenerated !== true;

const onCompleted = (evt: Event) => {
  const a = annotationOf(evt);
  if (isTracked(a)) {
    annotationHistory.recordCreate(a.annotationUID ?? "", a.metadata?.FrameOfReferenceUID ?? "");
  }
};

const onRemoved = (evt: Event) => {
  const a = annotationOf(evt);
  if (isTracked(a)) annotationHistory.recordDelete(a);
};

let started = false;

/**
 * Attach the singleton {@link annotationHistory} to Cornerstone's ANNOTATION_COMPLETED
 * / ANNOTATION_REMOVED events. Idempotent; returns a teardown that also detaches.
 */
export function startAnnotationHistory(): () => void {
  if (!started) {
    eventTarget.addEventListener(
      csToolsEnums.Events.ANNOTATION_COMPLETED,
      onCompleted as EventListener,
    );
    eventTarget.addEventListener(
      csToolsEnums.Events.ANNOTATION_REMOVED,
      onRemoved as EventListener,
    );
    started = true;
  }
  return () => {
    eventTarget.removeEventListener(
      csToolsEnums.Events.ANNOTATION_COMPLETED,
      onCompleted as EventListener,
    );
    eventTarget.removeEventListener(
      csToolsEnums.Events.ANNOTATION_REMOVED,
      onRemoved as EventListener,
    );
    started = false;
  };
}
