/**
 * Measurement export — read the annotations the user has drawn (Length, Angle,
 * ROIs, Probe) and serialize them to JSON or CSV. Framework-agnostic: only
 * `collectMeasurements` / `onMeasurementsChanged` touch Cornerstone; the
 * formatters are pure and testable with a plain array.
 *
 * TODO(sr-export): DICOM-SR (TID-1500) generation is a deliberate follow-up — it
 * needs a Part-10 writer (e.g. dcmjs) and STOW-RS upload, which we don't depend
 * on yet. The `Measurement` shape below is intentionally SR-friendly (frame of
 * reference, image id, world points, coded stats) so a future builder consumes
 * it directly.
 */
import { annotation } from "@cornerstonejs/tools";
import { Enums as csToolsEnums } from "@cornerstonejs/tools";
import { eventTarget } from "@cornerstonejs/core";

/** One per-target statistic (a tool may emit several, keyed by target id). */
export interface MeasurementStat {
  /** Raw cachedStats target key, e.g. `"imageId:wadors:…"`. */
  target: string;
  /** Canonical name: `length` | `angle` | `area` | `mean` | `max` | `min` | `stdDev` | `value`. */
  name: string;
  value: number;
  /** Display unit as stored by Cornerstone (`mm`, `mm²`, `deg`, `HU`, …) or `""`. */
  unit: string;
}

export interface Measurement {
  annotationUID: string;
  /** Cornerstone tool name: `Length` | `Angle` | `RectangleROI` | `EllipticalROI` | `Probe`. */
  tool: string;
  label: string;
  imageId: string;
  frameOfReferenceUID: string;
  stats: MeasurementStat[];
  /** World-space handle points; each is `[x, y, z]`. */
  points: [number, number, number][];
}

const KNOWN_TOOLS = new Set(["Length", "Angle", "RectangleROI", "EllipticalROI", "Probe"]);

/** Minimal shape we read from a Cornerstone annotation (avoids deep type coupling). */
interface RawAnnotation {
  annotationUID?: string;
  autoGenerated?: boolean;
  metadata?: { toolName?: string; referencedImageId?: string; FrameOfReferenceUID?: string };
  data?: {
    label?: string;
    handles?: { points?: number[][] };
    cachedStats?: Record<string, Record<string, unknown>>;
  };
}

const finite = (v: unknown): number | null =>
  typeof v === "number" && Number.isFinite(v) ? v : null;
const unitOf = (u: unknown): string => (typeof u === "string" ? u : "");

function extractStats(
  tool: string,
  cachedStats: Record<string, Record<string, unknown>> | undefined,
): MeasurementStat[] {
  if (!cachedStats) return [];
  const out: MeasurementStat[] = [];
  for (const [target, s] of Object.entries(cachedStats)) {
    if (!s || typeof s !== "object") continue;
    const push = (name: string, value: number | null, unit: unknown) => {
      if (value !== null) out.push({ target, name, value, unit: unitOf(unit) });
    };
    if (tool === "Length") {
      push("length", finite(s.length), s.unit);
    } else if (tool === "Angle") {
      // cachedStats.angle is ALREADY in degrees; "Incomplete Angle"/NaN is skipped by finite().
      push("angle", finite(s.angle), "deg");
    } else if (tool === "RectangleROI" || tool === "EllipticalROI") {
      push("area", finite(s.area), s.areaUnit);
      push("mean", finite(s.mean), s.modalityUnit);
      push("max", finite(s.max), s.modalityUnit);
      push("min", finite(s.min), s.modalityUnit);
      push("stdDev", finite(s.stdDev), s.modalityUnit);
    } else if (tool === "Probe") {
      const value = s.value;
      const unit = s.modalityUnit;
      if (Array.isArray(value)) {
        value.forEach((v, i) =>
          push(`value[${i}]`, finite(v), Array.isArray(unit) ? unit[i] : unit),
        );
      } else {
        push("value", finite(value), unit);
      }
    }
  }
  return out;
}

/**
 * Collect all current measurement annotations, normalized. `getAll` is injectable
 * for testing; it defaults to Cornerstone's global annotation state, which returns
 * a flat `Annotation[]` (not grouped). Unknown/auto-generated annotations are skipped.
 */
export function collectMeasurements(
  getAll: () => RawAnnotation[] = () => annotation.state.getAllAnnotations() as RawAnnotation[],
): Measurement[] {
  return (getAll() ?? [])
    .filter((a) => KNOWN_TOOLS.has(a?.metadata?.toolName ?? "") && a?.autoGenerated !== true)
    .map((a) => ({
      annotationUID: a.annotationUID ?? "",
      tool: a.metadata!.toolName!,
      label: a.data?.label ?? "",
      imageId: a.metadata?.referencedImageId ?? "",
      frameOfReferenceUID: a.metadata?.FrameOfReferenceUID ?? "",
      stats: extractStats(a.metadata!.toolName!, a.data?.cachedStats),
      points: (a.data?.handles?.points ?? []).map(
        (p) => [p[0], p[1], p[2]] as [number, number, number],
      ),
    }));
}

/** Subscribe to annotation create/modify/remove; returns an unsubscribe fn. */
export function onMeasurementsChanged(cb: () => void): () => void {
  const events = [
    csToolsEnums.Events.ANNOTATION_COMPLETED,
    csToolsEnums.Events.ANNOTATION_MODIFIED,
    csToolsEnums.Events.ANNOTATION_REMOVED,
  ];
  for (const e of events) eventTarget.addEventListener(e, cb as EventListener);
  return () => {
    for (const e of events) eventTarget.removeEventListener(e, cb as EventListener);
  };
}

/** Serialize measurements to a JSON document with provenance. `now` is injectable. */
export function measurementsToJson(
  measurements: Measurement[],
  now: () => string = () => new Date().toISOString(),
): string {
  return JSON.stringify(
    {
      schema: "orbidicom.measurements/v1",
      exportedAt: now(),
      count: measurements.length,
      measurements,
    },
    null,
    2,
  );
}

const CSV_COLUMNS = [
  "annotationUID",
  "tool",
  "label",
  "imageId",
  "frameOfReferenceUID",
  "target",
  "statName",
  "statValue",
  "statUnit",
  "points",
  "pointCount",
] as const;

/** RFC-4180 field escaping: quote iff it contains a comma, quote, CR or LF. */
const csvEsc = (v: string): string => (/[",\r\n]/.test(v) ? `"${v.replace(/"/g, '""')}"` : v);

/**
 * Serialize measurements to CSV (RFC-4180, `\r\n` terminators). Long format: one
 * row per statistic; an annotation with no finite stats still emits one row so it
 * isn't silently dropped.
 */
export function measurementsToCsv(measurements: Measurement[]): string {
  const rows: string[] = [CSV_COLUMNS.join(",")];
  for (const m of measurements) {
    const pts = m.points.map((p) => p.join(" ")).join("; ");
    const base = [m.annotationUID, m.tool, m.label, m.imageId, m.frameOfReferenceUID];
    const statRows: MeasurementStat[] = m.stats.length
      ? m.stats
      : [{ target: "", name: "", value: NaN, unit: "" }];
    for (const st of statRows) {
      const statVal = Number.isFinite(st.value) ? String(st.value) : "";
      const cells = [...base, st.target, st.name, statVal, st.unit, pts, String(m.points.length)];
      rows.push(cells.map((c) => csvEsc(String(c))).join(","));
    }
  }
  return rows.join("\r\n");
}
